### ISSUE TITLE
error loading acs5 variables

### ISSUE THREAD

**Issue by abuabara** [walkerke/tidycensus#21] opened 2017-07-27 04:15 UTC
Since today when I am trying to load the ACS table of variables I'm getting an error, and the table is not being loaded. The decennial table is just fine, as well the actual acs5 data sets I use.

I tried few tricks, without success. Just wondering if it is happening due a kind of packages update I may have done, or even because I'm using R on MacOS.

I appreciate your help. Thank you in advance!!

_> v15_acs5 <- load_variables(2015, "acs5", cache = TRUE) # ACS variables_
**Error in bind_rows_(x, .id) : Argument 6 must be length 1, not 0**

**Comment by walkerke** [comment] 2017-07-27 14:32
I can reproduce the error.  Let me look into this and I'll get back to you.

**Comment by walkerke** [comment] 2017-07-29 05:05
This recent update is breaking the function: 

https://www.census.gov/data/developers/updates/valid-values-now-presented-for-categorical-variables.html

I now know what the cause of the error is, and I'm working on a fix.

**Comment by walkerke** [comment] 2017-08-02 20:40
This is fixed in https://github.com/walkerke/tidycensus/commit/c1c5ec57d67ddfad7514cba9d03ac2a429c07735.  I have a little more cleaning up to do and then I'll get the updates to CRAN.

**Closed by walkerke** 2017-08-02 20:40 UTC
