### ISSUE TITLE
get_acs() error when output = "tidy"

### ISSUE THREAD

**Issue by mfherman** [walkerke/tidycensus#53] opened 2018-01-08 21:08 UTC
Hi Kyle,

I'm having trouble using "tidy" output from `get_acs` with version 0.4. I've tried a few different tables, variables, years, etc. and keep getting a similar error when I use tidy output. When I use wide output, everything is working as expected. The error persists with both the CRAN and GitHub versions of tidycensus.

See below for reprex:

``` r
library(tidycensus)

# tidy output
get_acs(
  state = "NY",
  geography = "county",
  variables = "B01003_001",
  survey = "acs5",
  year = 2016,
  geometry = FALSE,
  output = "tidy"
)
#> Please note: `get_acs()` now defaults to a year or endyear of 2016.
#> Error: Duplicate identifiers for rows (1, 63), (2, 64), (3, 65), (4, 66), (5, 67), (6, 68), (7, 69), (8, 70), (9, 71), (10, 72), (11, 73), (12, 74), (13, 75), (14, 76), (15, 77), (16, 78), (17, 79), (18, 80), (19, 81), (20, 82), (21, 83), (22, 84), (23, 85), (24, 86), (25, 87), (26, 88), (27, 89), (28, 90), (29, 91), (30, 92), (31, 93), (32, 94), (33, 95), (34, 96), (35, 97), (36, 98), (37, 99), (38, 100), (39, 101), (40, 102), (41, 103), (42, 104), (43, 105), (44, 106), (45, 107), (46, 108), (47, 109), (48, 110), (49, 111), (50, 112), (51, 113), (52, 114), (53, 115), (54, 116), (55, 117), (56, 118), (57, 119), (58, 120), (59, 121), (60, 122), (61, 123), (62, 124)

# wide output
get_acs(
  state = "NY",
  geography = "county",
  variables = "B01003_001",
  survey = "acs5",
  year = 2016,
  geometry = FALSE,
  output = "wide"
)
#> Please note: `get_acs()` now defaults to a year or endyear of 2016.
#> # A tibble: 62 x 4
#>    GEOID NAME                         B01003_001E B01003_001M
#>    <chr> <chr>                              <dbl>       <dbl>
#>  1 36001 Albany County, New York           307891          NA
#>  2 36003 Allegany County, New York          47700          NA
#>  3 36005 Bronx County, New York           1436785          NA
#>  4 36007 Broome County, New York           197381          NA
#>  5 36009 Cattaraugus County, New York       78506          NA
#>  6 36011 Cayuga County, New York            78783          NA
#>  7 36013 Chautauqua County, New York       131748          NA
#>  8 36015 Chemung County, New York           87742          NA
#>  9 36017 Chenango County, New York          49286          NA
#> 10 36019 Clinton County, New York           81505          NA
#> # ... with 52 more rows
```
Created on 2018-01-08 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

```r
Session info ------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.402)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-01-08                  

Packages ----------------------------------------------------------------------------------------------
 package     * version    date       source                               
 assertthat    0.2.0      2017-04-11 CRAN (R 3.4.0)                       
 backports     1.1.2      2017-12-13 CRAN (R 3.4.3)                       
 base        * 3.4.3      2017-12-07 local                                
 bindr         0.1        2016-11-13 cran (@0.1)                          
 bindrcpp    * 0.2        2017-06-17 CRAN (R 3.4.0)                       
 callr         1.0.0.9000 2018-01-07 Github (r-lib/callr@550fa6b)         
 class         7.3-14     2015-08-30 CRAN (R 3.4.3)                       
 classInt      0.1-24     2017-04-16 CRAN (R 3.4.0)                       
 cli           1.0.0      2017-11-05 CRAN (R 3.4.2)                       
 clipr         0.4.0      2017-11-03 CRAN (R 3.4.2)                       
 compiler      3.4.3      2017-12-07 local                                
 crayon        1.3.4      2017-11-15 Github (r-lib/crayon@b5221ab)        
 curl          3.1        2017-12-24 local                                
 datasets    * 3.4.3      2017-12-07 local                                
 DBI           0.7        2017-06-18 CRAN (R 3.4.0)                       
 debugme       1.1.0      2017-10-22 CRAN (R 3.4.2)                       
 devtools      1.13.4     2017-11-09 CRAN (R 3.4.2)                       
 digest        0.6.13     2017-12-14 CRAN (R 3.4.3)                       
 dplyr         0.7.4.9000 2018-01-08 Github (tidyverse/dplyr@e4b34cd)     
 e1071         1.6-8      2017-02-02 CRAN (R 3.4.0)                       
 evaluate      0.10.1     2017-06-24 CRAN (R 3.4.0)                       
 foreign       0.8-69     2017-06-22 CRAN (R 3.4.3)                       
 git2r         0.21.0     2018-01-04 CRAN (R 3.4.3)                       
 glue          1.2.0      2017-10-29 CRAN (R 3.4.2)                       
 graphics    * 3.4.3      2017-12-07 local                                
 grDevices   * 3.4.3      2017-12-07 local                                
 grid          3.4.3      2017-12-07 local                                
 hms           0.4.0      2017-11-23 CRAN (R 3.4.3)                       
 htmltools     0.3.6      2017-04-28 CRAN (R 3.4.0)                       
 htmlwidgets   0.9        2017-07-10 CRAN (R 3.4.0)                       
 httr          1.3.1      2017-12-24 Github (hadley/httr@6b2dadc)         
 jsonlite      1.5        2017-06-01 CRAN (R 3.4.0)                       
 knitr         1.18       2017-12-27 CRAN (R 3.4.3)                       
 lattice       0.20-35    2017-03-25 CRAN (R 3.4.3)                       
 magrittr      1.5        2014-11-22 CRAN (R 3.4.0)                       
 maptools      0.9-2      2017-03-25 CRAN (R 3.4.0)                       
 memoise       1.1.0      2017-04-21 CRAN (R 3.4.0)                       
 methods     * 3.4.3      2017-12-07 local                                
 pillar        1.0.1      2017-11-27 CRAN (R 3.4.3)                       
 pkgconfig     2.0.1      2017-03-21 cran (@2.0.1)                        
 processx      2.0.0.1    2017-07-30 CRAN (R 3.4.1)                       
 purrr         0.2.4.9000 2017-12-09 Github (tidyverse/purrr@62b135a)     
 R6            2.2.2      2017-06-17 CRAN (R 3.4.0)                       
 rappdirs      0.3.1      2016-03-28 CRAN (R 3.4.0)                       
 Rcpp          0.12.14    2017-11-23 CRAN (R 3.4.3)                       
 readr         1.1.1.9000 2017-12-24 Github (tidyverse/readr@5415cc1)     
 reprex        0.1.1.9000 2018-01-07 Github (tidyverse/reprex@6453eff)    
 rgdal         1.2-16     2017-11-21 CRAN (R 3.4.2)                       
 rlang         0.1.6.9002 2018-01-08 Github (tidyverse/rlang@f6e234f)     
 rmarkdown     1.8        2017-11-17 CRAN (R 3.4.2)                       
 rprojroot     1.3-2      2018-01-03 CRAN (R 3.4.3)                       
 rstudioapi    0.7        2017-09-07 CRAN (R 3.4.1)                       
 rvest         0.3.2.9000 2017-12-24 Github (hadley/rvest@9a51a5d)        
 sf            0.6-0      2018-01-06 CRAN (R 3.4.3)                       
 sp            1.2-6      2018-01-05 CRAN (R 3.4.3)                       
 stats       * 3.4.3      2017-12-07 local                                
 stringi       1.1.6      2017-11-17 CRAN (R 3.4.2)                       
 stringr       1.2.0.9000 2018-01-08 Github (tidyverse/stringr@c8bbc0d)   
 tibble        1.4.1.9000 2018-01-06 Github (tidyverse/tibble@f965ac0)    
 tidycensus  * 0.4        2018-01-08 Github (walkerke/tidycensus@4ab9006) 
 tidyr         0.7.2.9000 2018-01-08 Github (tidyverse/tidyr@7e894a3)     
 tidyselect    0.2.3.9000 2018-01-08 Github (tidyverse/tidyselect@d76ca3a)
 tigris        0.6.2      2018-01-04 CRAN (R 3.4.3)                       
 tools         3.4.3      2017-12-07 local                                
 udunits2      0.13       2016-11-17 CRAN (R 3.4.0)                       
 units         0.5-0      2018-01-07 CRAN (R 3.4.3)                       
 utf8          1.1.3      2018-01-03 CRAN (R 3.4.3)                       
 utils       * 3.4.3      2017-12-07 local                                
 uuid          0.1-2      2015-07-28 CRAN (R 3.4.0)                       
 whisker       0.3-2      2013-04-28 CRAN (R 3.4.0)                       
 withr         2.1.1.9000 2017-12-24 Github (jimhester/withr@df18523)     
 xml2          1.1.1      2017-01-24 CRAN (R 3.4.0)                       
 yaml          2.1.16     2017-12-12 CRAN (R 3.4.3)   

```

**Comment by walkerke** [comment] 2018-01-08 22:36
I can't reproduce this error; however I notice you are on the dev versions of the tidyverse packages while I am testing on the CRAN versions.  I wonder if an update to tidyr dev is breaking things.  I'll investigate.

**Comment by walkerke** [comment] 2018-01-08 22:59
I just tested against the development version of tidyr and I can reproduce the error.  I note in the upcoming release notes for tidyr: (https://github.com/tidyverse/tidyr/commit/7e894a356da8ccab4dd5747993d3b5e9239621c6)

> There are no deliberate breaking changes in this release. However, a number of packages are failing with errors related to numbers of elements in columns, and row names. It is possible that these are accidental API changes or new bugs. If you see such an error in your package, I would sincerely appreciate a minimal reprex.

@hadley I'm tagging you here as you mentioned that you'd appreciate a reprex in this event which @mfherman has provided above.  @mfherman I'd just recommend rolling back to the CRAN version of tidyr for now while I look into this.  I did note that when I installed the GitHub version of tidyr I got several "missing file link" warnings; did this happen to you too @mfherman?

**Comment by walkerke** [comment] 2018-01-09 03:59
I've figured this out.  The `separate()` function in tidyr has changed in the development version in its interpretation of character positions as negative integers from the right-hand side of a string.  The issue is addressed here: https://github.com/tidyverse/tidyr/issues/315.  

tidycensus detects whether a column represents `estimate` or `moe` by extracting the last character of an ACS variable, which is always `E` or `M`.  In `separate()` in the CRAN version of tidyr, this is represented by `sep = -2`.  However, in the development version of tidyr, splitting at the last character is represented by `sep = -1`.  

As such I don't really have a satisfactory fix for this until the new version of tidyr is on CRAN, at which point I'll submit an updated tidycensus that will work with the new version.  @mfherman if you need the development version of tidyr I could create a new tidycensus branch that you can install from that would work.  Let me know what you think.  

I'll leave this issue open in case others encounter the problem, and close when updated versions of tidyr and tidycensus hit CRAN.

**Comment by mfherman** [comment] 2018-01-09 04:14
Nice detective work, @walkerke! I rolled back to CRAN tidyr and now it's working as expected. I don't need the dev version of tidyr so no need for a branch.

Thanks again for the package. After showing some of my grad school classmates how easy it is to access ACS data with tidycensus, they all want to learn R so they never have to use American FactFinder again!

**Comment by mfherman** [comment] 2018-01-09 06:00
I was thinking we could get around this by using `extract()` with some regex instead of `separate()` to extract the `E` or `M` and split into two columns:

```r
# from the get_acs() function
dat2 <- sub %>%
  gather(key = variable, value = value, -GEOID, -NAME) %>%
  extract(variable, into = c("variable", "type"), regex = "^(.*?)([EM])") %>%
  mutate(type = ifelse(type == "E", "estimate", "moe")) %>%
  spread(type, value)
```
This worked in some of my minimal testing with a variety of variables, but not sure if it would catch all of them? The change is in PR #54.

**Comment by hadley** [comment] 2018-01-09 14:02
Thanks - just added this to the readme:

* `separate()` now correctly uses -1 to refer to the far right position, 
  instead of -2. If you depended on this behaviour, you'll need to switch
  on `packageVersion("tidyr") > "0.7.2"`

(And I'd really recommend just using `packageVersion("tidyr")` rather than completely changing your approach)

**Comment by walkerke** [comment] 2018-01-09 19:53
Thanks @hadley!  I've followed your suggestion and fixed this in https://github.com/walkerke/tidycensus/commit/b5eb29406953ff0f1666273dcc2f26220733d656.  @mfherman I really appreciate you taking the time to make the pull request - any future PRs are quite welcome!

**Closed by walkerke** 2018-01-09 19:53 UTC

**Comment by mfherman** [comment] 2018-01-10 15:51
Thanks @walkerke! sf is now working for me with both CRAN and dev tidyr.
