### ISSUE TITLE
NAs returned for tract GEOID

### ISSUE THREAD

**Issue by sheffe** [walkerke/tidycensus#57] opened 2018-01-20 18:59 UTC
First - this package has saved me tons of time/stress - thank you!

Weird issue here. I am running the current CRAN edition 0.4. When I call get_acs() for tract geography, I see NAs in the `GEOID` column despite seeing what appear to be correct values for the tract `NAME`, `estimate`, and `moe`. This is a new issue for me after updating to 0.4.

This does not occur for all counties. In a recent pull of tracts for counties in some major urban areas, I had 100% missing GEOIDs for counties in AL, AZ, AR, CA, CO, CT, FL, GA, IL, IN, IA, and nothing missing for any other counties in my state sample. [I did not check every state; summary table to follow.]

`
> library(tidycensus)
> devtools::session_info()
Session info -------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Zulu                        
 date     2018-01-20                  
`

Packages 
 package    * version date       source        
 assertthat   0.2.0   2017-04-11 CRAN (R 3.4.2)
 base       * 3.4.2   2017-09-29 local         
 bindr        0.1     2016-11-13 CRAN (R 3.4.2)
 bindrcpp     0.2     2017-06-17 CRAN (R 3.4.2)
 compiler     3.4.2   2017-09-29 local         
 datasets   * 3.4.2   2017-09-29 local         
 DBI          0.7     2017-06-18 CRAN (R 3.4.2)
 devtools     1.13.3  2017-08-02 CRAN (R 3.4.2)
 digest       0.6.12  2017-01-27 CRAN (R 3.4.2)
 dplyr        0.7.4   2017-09-28 CRAN (R 3.4.2)
 foreign      0.8-69  2017-06-21 CRAN (R 3.4.0)
 glue         1.1.1   2017-06-21 CRAN (R 3.4.2)
 graphics   * 3.4.2   2017-09-29 local         
 grDevices  * 3.4.2   2017-09-29 local         
 grid         3.4.2   2017-09-29 local         
 hms          0.3     2016-11-22 CRAN (R 3.4.2)
 httr         1.3.1   2017-08-20 CRAN (R 3.4.2)
 jsonlite     1.5     2017-06-01 CRAN (R 3.4.2)
 lattice      0.20-35 2017-03-25 CRAN (R 3.3.3)
 magrittr     1.5     2014-11-22 CRAN (R 3.4.2)
 maptools     0.9-2   2017-03-25 CRAN (R 3.4.2)
 memoise      1.1.0   2017-04-21 CRAN (R 3.4.2)
 methods    * 3.4.2   2017-09-29 local         
 pkgconfig    2.0.1   2017-03-21 CRAN (R 3.4.2)
 purrr        0.2.4   2017-10-18 CRAN (R 3.4.2)
 R6           2.2.2   2017-06-17 CRAN (R 3.4.2)
 rappdirs     0.3.1   2016-03-28 CRAN (R 3.4.2)
 Rcpp         0.12.13 2017-09-28 CRAN (R 3.4.2)
 readr        1.1.1   2017-05-16 CRAN (R 3.4.2)
 rgdal        1.2-13  2017-10-07 CRAN (R 3.4.2)
 rgeos        0.3-25  2017-09-25 CRAN (R 3.4.2)
 rlang        0.1.2   2017-08-09 CRAN (R 3.4.2)
 rvest        0.3.2   2016-06-17 CRAN (R 3.4.2)
 sf           0.5-4   2017-08-28 CRAN (R 3.4.2)
 sp           1.2-5   2017-06-29 CRAN (R 3.4.2)
 stats      * 3.4.2   2017-09-29 local         
 stringi      1.1.5   2017-04-07 CRAN (R 3.4.2)
 stringr      1.2.0   2017-02-18 CRAN (R 3.4.2)
 tibble       1.3.4   2017-08-22 CRAN (R 3.4.2)
 tidycensus * 0.4     2018-01-02 CRAN (R 3.4.2)
 tidyr        0.7.2   2017-10-16 CRAN (R 3.4.2)
 tigris       0.5.3   2017-05-26 CRAN (R 3.4.2)
 tools        3.4.2   2017-09-29 local         
 udunits2     0.13    2016-11-17 CRAN (R 3.4.2)
 units        0.4-6   2017-08-27 CRAN (R 3.4.2)
 utils      * 3.4.2   2017-09-29 local         
 uuid         0.1-2   2015-07-28 CRAN (R 3.4.2)
 withr        2.0.0   2017-07-28 CRAN (R 3.4.2)
 xml2         1.1.1   2017-01-24 CRAN (R 3.4.2)
 yaml         2.1.14  2016-11-12 CRAN (R 3.4.2)

`
> na_check <- get_acs(geography = "tract", 
                     state = "01", 
                     county = "001", 
                     table = "B01001", 
                     geometry = FALSE, 
                     year = 2015, 
                     survey = "acs5", 
                     cache_table = TRUE, 
                     keep_geo_vars = FALSE,
                     key = "foo")
Please note: "get_acs()" now defaults to a year or endyear of 2016.
Loading ACS5 variables for 2015 from table B01001 and caching the dataset for faster future access.
> sum(is.na(na_check$GEOID))/nrow(na_check)
[1] 1
`

Above I show this result when calling the state/county by FIPS code; I get the same result in GEOID NAs when calling by the text names of state/county. What *does* look different when I call get_acs() using text names -- the normal message on FIPS translations is repeated 3 times instead of appearing once.

`
> na_check <- get_acs(geography = "tract", 
                     state = "AL", 
                     county = "Autauga County", 
                     table = "B01001", 
                     geometry = FALSE, 
                     year = 2014, 
                     survey = "acs5", 
                     cache_table = TRUE, 
                     keep_geo_vars = FALSE,
                     key = "foo")
Please note: "get_acs()" now defaults to a year or endyear of 2016.
Loading ACS5 variables for 2014 from table B01001 and caching the dataset for faster future access.
Using FIPS code '01' for state 'AL'
Using FIPS code '001' for 'Autauga County'
Using FIPS code '01' for state 'AL'
Using FIPS code '001' for 'Autauga County'
Using FIPS code '01' for state 'AL'
Using FIPS code '001' for 'Autauga County'
> sum(is.na(na_check$GEOID))/nrow(na_check)
[1] 1
`

Last thing -- these issues are not unique to the table ID (B01001) and occurred for exactly the same set of states for every table I tried [>40 randomly selected].

Failing states:
<img width="247" alt="screenshot 2018-01-20 13 55 42" src="https://user-images.githubusercontent.com/3778733/35186899-cc97e1ca-fde9-11e7-818c-9525e915ad15.png">

Working states:
<img width="196" alt="screenshot 2018-01-20 13 56 12" src="https://user-images.githubusercontent.com/3778733/35186902-d38c29be-fde9-11e7-82b0-71cdc017383a.png">

**Comment by walkerke** [comment] 2018-01-20 20:38
Thanks for your kind words!  

I'm unable to reproduce the error.  I'll investigate this.

**Comment by sheffe** [comment] 2018-01-20 22:44
One possible lead - in the initial report, the states that returned GEOID NA were in alphabetical order up to Iowa. I verified that it's not a case of dropped leading 0s in state FIPS, like you sometimes see with ZIPs as integers (2138 for 02138). Between this and the repeated messages when translating a state/county name input to a FIPS code, maybe something related to input string handling? I'm starting to walk through that now.

Re: reproducing, on the Ubuntu EC2 instance from the initial report, I'm getting the same result (all NAs) after clean install of tidycensus, and same after clean install of all dependencies held to the same version number as in the initial report. I can confirm that tidycensus 4.0 works as intended on MacOS (x86_64, darwin15.6.0) running the same R version (3.4.2). The only difference in tidycensus dependencies that I can see is an updated stringi (failure case running 1.1.5, success case running 1.1.6). I'll try a few more tests.

**Comment by walkerke** [comment] 2018-02-01 14:24
Hey John - I've been testing on an Ubuntu instance and the above code is working as expected.  I had a hunch that something might be going on with regards to https://github.com/walkerke/tidycensus/blob/master/R/acs.R#L244; this is how tidycensus gets around the 50-variable limitation for Census API calls as it makes multiple calls to the API and stitches the datasets together.   My `sessionInfo()`: 

```
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] bindrcpp_0.2       tidycensus_0.4.1   tigris_0.6.2       forcats_0.2.0     
 [5] stringr_1.2.0      dplyr_0.7.4        purrr_0.2.4        readr_1.1.1       
 [9] tidyr_0.8.0        tibble_1.4.2       ggplot2_2.2.1.9000 tidyverse_1.2.1   
[13] sf_0.6-0           RBackend_4.8.6    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15       stringdist_0.9.4.2 lubridate_1.7.1    lattice_0.20-35   
 [5] class_7.3-14       utf8_1.1.3         assertthat_0.2.0   psych_1.7.8       
 [9] R6_2.2.2           cellranger_1.1.0   plyr_1.8.4         evaluate_0.10.1   
[13] e1071_1.6-8        httr_1.3.1         pillar_1.1.0       rlang_0.1.6.9003  
[17] curl_3.1           uuid_0.1-2         lazyeval_0.2.1     readxl_1.0.0      
[21] rstudioapi_0.7     praise_1.0.0       rgdal_1.2-16       udunits2_0.13     
[25] foreign_0.8-69     munsell_0.4.3      broom_0.4.3        compiler_3.4.2    
[29] modelr_0.1.1       pkgconfig_2.0.1    testwhat_4.3.1     mnormt_1.5-5      
[33] tidyselect_0.2.3   crayon_1.3.4       withr_2.1.1.9000   rappdirs_0.3.1    
[37] grid_3.4.2         nlme_3.1-131       jsonlite_1.5       gtable_0.2.0      
[41] DBI_0.7            magrittr_1.5       units_0.5-1        scales_0.5.0.9000 
[45] cli_1.0.0          stringi_1.1.6      reshape2_1.4.3     sp_1.2-7          
[49] xml2_1.2.0         RCompletion_0.1.23 rjson_0.2.15       tools_3.4.2       
[53] glue_1.2.0         markdown_0.8       hms_0.4.1          parallel_3.4.2    
[57] colorspace_1.3-2   maptools_0.9-2     classInt_0.1-24    rvest_0.3.2       
[61] bindr_0.1          haven_1.1.1
```

Are you still getting the error on your Ubuntu instance?

**Comment by sheffe** [comment] 2018-02-28 14:31
@walkerke have my EC2 instance back up again, and seeing the same issue with 0.4.1 (CRAN edition as of today 28 Feb) and the master on Github.

```r
devtools::install_version("tidycensus", version = "0.4.1", repos = "http://cran.us.r-project.org")
library(tidycensus)
na_check <- get_acs(geography = "tract",
                    state = "AL",
                    county = "Autauga County",
                    table = "B01001",
                    geometry = FALSE,
                    year = 2014,
                    survey = "acs5",
                    cache_table = TRUE,
                    keep_geo_vars = FALSE,
                    key = "foo")

R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2     tidycensus_0.4.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15     pillar_1.2.1     compiler_3.4.2   bindr_0.1        class_7.3-14     tools_3.4.2      digest_0.6.12    uuid_0.1-2       jsonlite_1.5    
[10] memoise_1.1.0    tibble_1.4.2     lattice_0.20-35  pkgconfig_2.0.1  rlang_0.2.0      rstudioapi_0.7   DBI_0.7          curl_3.0         yaml_2.1.14     
[19] rgdal_1.2-16     e1071_1.6-8      withr_2.0.0      dplyr_0.7.4      httr_1.3.1       stringr_1.3.0    xml2_1.2.0       hms_0.3          rappdirs_0.3.1  
[28] devtools_1.13.3  tigris_0.6.2     tidyselect_0.2.4 classInt_0.1-24  grid_3.4.2       glue_1.2.0       sf_0.6-0         R6_2.2.2         foreign_0.8-69  
[37] sp_1.2-7         readr_1.1.1      tidyr_0.8.0      purrr_0.2.4      udunits2_0.13    magrittr_1.5     units_0.5-1      maptools_0.9-2   assertthat_0.2.0
[46] rvest_0.3.2      stringi_1.1.6
```

And using current master on github (identical calls / sessionInfo but with devtools::install_github("walkerke/tidycensus")) I see the same thing...

<img width="596" alt="screenshot 2018-02-28 09 25 00" src="https://user-images.githubusercontent.com/3778733/36793003-2e403956-1c6a-11e8-9080-a0481d08e968.png">

**Comment by sheffe** [comment] 2018-02-28 14:52
For what it's worth, comparing the results of the MacOS pull to the Ubuntu pull:

- everything in estimate/moe is identical 
- all variables are present and correctly ordered 
- there are no census tracts dropped and the NAME contents and arrangement are equivalent

The error still only happens for the subset of states noted above. It occurs whether we call state and county by string name ("AL", "Autauga County") or FIPS code ("01", "001") or any mixture of FIPS/string name. It happens for tract and for block group. It *also* occurs when we use county=NULL and pull county geographies for state = "AL".

I wondered about the validate_state() and validate_county() calls and took a look at the df for `fips_codes` but did not see anything obvious. If that were a problem, it should break well before returning the correct data, and I did some manual testing and everything worked just fine.

**Comment by walkerke** [comment] 2018-02-28 19:37
Thanks again for checking!  I've just run your code successfully on RStudio Cloud using the same Ubuntu version as you.  Here are my results: 

```r
> na_check
# A tibble: 588 x 5
   GEOID       NAME                                      variable   estimate   moe
   <chr>       <chr>                                     <chr>         <dbl> <dbl>
 1 01001020100 Census Tract 201, Autauga County, Alabama B01001_001    1900.  180.
 2 01001020100 Census Tract 201, Autauga County, Alabama B01001_002     944.  127.
 3 01001020100 Census Tract 201, Autauga County, Alabama B01001_003      24.   26.
 4 01001020100 Census Tract 201, Autauga County, Alabama B01001_004      68.   42.
 5 01001020100 Census Tract 201, Autauga County, Alabama B01001_005      93.   43.
 6 01001020100 Census Tract 201, Autauga County, Alabama B01001_006      54.   36.
 7 01001020100 Census Tract 201, Autauga County, Alabama B01001_007      22.   23.
 8 01001020100 Census Tract 201, Autauga County, Alabama B01001_008       9.   14.
 9 01001020100 Census Tract 201, Autauga County, Alabama B01001_009      24.   27.
10 01001020100 Census Tract 201, Autauga County, Alabama B01001_010      60.   41.
# ... with 578 more rows
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2     tidycensus_0.4.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15     pillar_1.2.0     compiler_3.4.3   bindr_0.1        class_7.3-14    
 [6] tools_3.4.3      uuid_0.1-2       jsonlite_1.5     tibble_1.4.2     lattice_0.20-35 
[11] pkgconfig_2.0.1  rlang_0.2.0.9000 cli_1.0.0        rstudioapi_0.7   DBI_0.7         
[16] curl_3.1         yaml_2.1.16      rgdal_1.2-16     e1071_1.6-8      dplyr_0.7.4     
[21] httr_1.3.1       stringr_1.3.0    xml2_1.2.0       rappdirs_0.3.1   tigris_0.6.2    
[26] hms_0.4.1        tidyselect_0.2.3 classInt_0.1-24  grid_3.4.3       glue_1.2.0      
[31] sf_0.6-0         R6_2.2.2         foreign_0.8-69   sp_1.2-7         tidyr_0.8.0     
[36] purrr_0.2.4      readr_1.1.1      udunits2_0.13    magrittr_1.5     units_0.5-1     
[41] maptools_0.9-2   assertthat_0.2.0 rvest_0.3.2      utf8_1.1.3       stringi_1.1.6   
[46] crayon_1.3.4   
```

The only differences I see at first glance are: 
* You are on R 3.4.2, I'm on R 3.4.3
* You have a different LAPACK version (not sure why that would matter, though)

I'll keep working on this one!

**Comment by sheffe** [comment] 2018-03-01 14:47
@walkerke Okay - read the release notes on 3.4.2 --> 3.4.3 and didn't see anything obvious, but I'll update to 3.4.3 later today / do a clean install of package dependencies and rerun once that's finished. We've resolved the practical issue by pulling data using an earlier version of tidycensus, but I'd still like to help figure out why. Thanks as always!

**Comment by tarakc02** [comment] 2018-03-04 05:04
I just ran into the same problem as @sheffe, and googling got me here. I'm also on Ubuntu, R 3.4.2. I fiddled around with tracing back the error, and found it is happening right here: https://github.com/walkerke/tidycensus/blob/master/R/acs.R#L288 (and again a few lines down for output = "wide"). Some GEOIDs are being converted to NA during that part. I tested a few values to be sure, and:

```
# using a GEOID that would be in CA
"060014001001" < -100000000
## [1] TRUE

# making up a GEOID in Georgia
"130014001001" < -100000000
## [1] TRUE

# but in Kansas:
"200014001001" < -100000000
## [1] FALSE
```

Those results explain the pattern in which states work/don't work in @sheffe's original post. I cloned and  commented out lines 288 and 305 before re-running the code just to be sure, and the missing GEOIDs did in fact come back.

**Comment by walkerke** [comment] 2018-03-04 11:46
@tarakc02 @sheffe I was wondering if it was that... I just could never reproduce it myself.  The reason why I did that is to solve https://github.com/walkerke/tidycensus/issues/29 as NAs for margins of error for various variables are represented as a variety of different negative integers - so that was to take care of all of them.  

I note on Ubuntu, R 3.4.3: 

```r
> "130014001001" < -100000000
[1] FALSE
> "060014001001" < -100000000
[1] FALSE
```

However I will still patch this for users who need to be on earlier R versions, at which time I'll close this issue.

**Comment by walkerke** [comment] 2018-03-04 12:29
I believe https://github.com/walkerke/tidycensus/commit/13a7c67f45ad77649ee406e402c419e01f0d3cdf should now solve this issue.  Would either of you mind testing?

**Comment by tarakc02** [comment] 2018-03-04 16:51
This works as expected for me. And replacing the exact values that are used to encode NA seems to get around the unpredictable nature of `<` on certain character values. In case something similar comes up again, or just for the sake of more clearly communicating what's happening, a safe approach could be to explicitly apply the transformation only to numeric columns. I thought of two ways to do that:

Using `dplyr::mutate_if`:
```
dat2 <- dplyr::mutate_if(dat2, is.numeric, ~ifelse(. < -100000000, NA, .))
```
(the predicate in `ifelse` could also just look for the -222222222, -555555555, and -888888888)

Using vapply et al:
```
numeric_indexes <- vapply(dat2, is.numeric, FUN.VALUE = logical(1))
dat2[, numeric_indexes] <- lapply(dat2[ , numeric_indexes],
                                  function(x) ifelse(x < -100000000, NA, x))
```

Again, the current version works for me as it is, those are just FYI. Thanks for this great package, I particularly appreciate being able to pull the relevant geometries along with the estimates and MOEs, as well as being able to specify the confidence level for the MOEs.

**Comment by walkerke** [comment] 2018-03-04 16:53
Thanks so much, glad to hear it is working!  I'm closing this issue.

**Closed by walkerke** 2018-03-04 16:53 UTC
