### ISSUE TITLE
get_acs Fails Inside Functions for 2010-2014 End Dates 

### ISSUE THREAD

**Issue by RyanWalch** [walkerke/tidycensus#145] opened 2019-01-15 18:40 UTC
get_acs is failing when I try and pass a year or state to it inside a function for years between 2010 and 2014 (it works fine for 2015 and 2016 weirdly).  The code I am running: 

```
library(tidycensus)


get_state_demographic_data <- function(the_state,the_year){


  
  options(tigris_use_cache = TRUE) #keep chached version of data)

 
  state_income <- get_acs(geography = 'tract',
                          table = c("B19301"),
                          state = the_state,
                          year = the_year,
                          survey = 'acs5',
                          geometry = TRUE,
                          cache_table = TRUE)
  
}

df <- get_state_demographic_data('AZ',2010)
```

The error I get is 

` Error in get_acs(geography = "tract", table = c("B19301"), cache_table = TRUE,  : 
  object 'the_year' not found `

If I change the function call to the year 2015 it runs fine.  Running the following code in the browser works with no issues
```

state_income <- get_acs(geography = 'tract',
                          table = c("B19301"),
                          state = 'AZ',
                          year = 2016,
                          survey = 'acs5',
                          geometry = TRUE,
                          cache_table = TRUE)
```

**Comment by mfherman** [comment] 2019-01-15 19:51
This error is related to the way `get_acs()` re-calls itself when getting tracts in multiple states. See #136 for more discussion about this issue. Until `get_acs()` is re-factored, one workaround is to use `purrr::map()` to loop over all counties in a state to get tracts from each counties. Your function would look something like this:

``` r
library(tidycensus)
library(magrittr) # for the pipe operator

get_state_demographic_data <- function(the_state, the_year) {
  
  options(tigris_use_cache = TRUE) #keep chached version of data
  
  # get all counties in given state
  counties <- tidycensus::fips_codes %>%
    dplyr::filter(state == the_state)
  
  # loop over counties and get tracts for each county
  purrr::map(counties$county_code, 
       ~ get_acs(
         geography = 'tract',
         table = c("B19301"),
         state = the_state,
         county = .x,
         year = the_year,
         survey = 'acs5',
         geometry = TRUE,
         cache_table = TRUE
         )
       ) %>% 
    purrr::reduce(rbind)  # bind rows of all counties
}

df <- get_state_demographic_data('AZ', 2010)
#> Getting data from the 2006-2010 5-year ACS
#> Loading ACS5 variables for 2010 from table B19301 and caching the dataset for faster future access.

head(df)
#> Simple feature collection with 6 features and 5 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -110.0007 ymin: 35.68429 xmax: -109.0452 ymax: 36.99935
#> epsg (SRID):    4269
#> proj4string:    +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs
#>         GEOID                                         NAME   variable
#> 1 04001942600    Census Tract 9426, Apache County, Arizona B19301_001
#> 2 04001942700    Census Tract 9427, Apache County, Arizona B19301_001
#> 3 04001944000    Census Tract 9440, Apache County, Arizona B19301_001
#> 4 04001944100    Census Tract 9441, Apache County, Arizona B19301_001
#> 5 04001944201 Census Tract 9442.01, Apache County, Arizona B19301_001
#> 6 04001944202 Census Tract 9442.02, Apache County, Arizona B19301_001
#>   estimate  moe                       geometry
#> 1     6540 1535 MULTIPOLYGON (((-109.9341 3...
#> 2    10370 1419 MULTIPOLYGON (((-109.0454 3...
#> 3    13275 2123 MULTIPOLYGON (((-109.0461 3...
#> 4     7646 1031 MULTIPOLYGON (((-109.046 36...
#> 5    11828 4826 MULTIPOLYGON (((-109.6067 3...
#> 6     9911 2603 MULTIPOLYGON (((-109.3924 3...
```

<sup>Created on 2019-01-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by tfricker** [comment] 2019-02-06 16:58
I am having a similar issue with 2010--2014 end years---though no issue with 2015, 2016, or 2017 end years. I have tried the workaround and am still failing. My code is:
```
library(tidycensus)

us <- unique(fips_codes$state)[c(1, 3:8, 10:11, 13:51)]

us2010.sf <- reduce(map(us, function(x) {
  get_acs(state = x,
          geography = "tract", 
          variables = ("B01001_001E"),
          year = 2010,
          output = "wide",
          geometry = TRUE)
}),
rbind
)
```
The error I get is 

> Error: Result 1 is not a length 1 atomic vector
Called from: map_chr(county, function(x) {
    validate_county(state, x)
}) 

I have also tried looping over county codes in addition to state FIPS---to no avail. Any ideas?

**Comment by mfherman** [comment] 2019-02-06 17:27
Take a look at https://github.com/walkerke/tidycensus/issues/136#issuecomment-443362304 for some more detail about how to iterate over state/county combinations. Also note the wrinkle regarding changed county names in certain years.

I believe I have a working example of what you are trying to achieve below. Note, I did this for only 2 two states instead of all the ones you are trying to get to save some time when running the example code. 

And a last note, I've seen @walkerke suggest that [NHGIS](https://www.nhgis.org/) may be a better data source that tidycensus for these large data pulls at the tract/block group/block level.

``` r
library(tidyverse)
library(tidycensus)

options(tigris_use_cache = TRUE)

my_states <- unique(fips_codes$state)[c(1, 3)]

county_state <- tigris::counties(
  state = my_states,
  cb = TRUE,
  resolution = "20m",
  year = "2010",
  class = "sf"
)

us2010.sf <- reduce(
    map2(
    .x = county_state$STATEFP,
    .y = county_state$COUNTYFP,
    ~ get_acs(
        state = .x,
        county = .y,
        geography = "tract", 
        variables = ("B01001_001E"),
        year = 2010,
        output = "wide",
        geometry = TRUE
        )
      ),
    rbind
   )
#> Getting data from the 2006-2010 5-year ACS

head(us2010.sf)
#> Simple feature collection with 6 features and 4 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -86.51038 ymin: 32.424 xmax: -86.41135 ymax: 32.50516
#> epsg (SRID):    4269
#> proj4string:    +proj=longlat +datum=NAD83 +no_defs
#>         GEOID                                      NAME B01001_001E
#> 1 01001020100 Census Tract 201, Autauga County, Alabama        1809
#> 2 01001020200 Census Tract 202, Autauga County, Alabama        2020
#> 3 01001020300 Census Tract 203, Autauga County, Alabama        3543
#> 4 01001020400 Census Tract 204, Autauga County, Alabama        4840
#> 5 01001020500 Census Tract 205, Autauga County, Alabama        9938
#> 6 01001020600 Census Tract 206, Autauga County, Alabama        3402
#>   B01001_001M                       geometry
#> 1         155 MULTIPOLYGON (((-86.50871 3...
#> 2         258 MULTIPOLYGON (((-86.47525 3...
#> 3         332 MULTIPOLYGON (((-86.45369 3...
#> 4         260 MULTIPOLYGON (((-86.44742 3...
#> 5         543 MULTIPOLYGON (((-86.41135 3...
#> 6         311 MULTIPOLYGON (((-86.46112 3...
```

<sup>Created on 2019-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by gpreston958** [comment] 2019-02-12 22:58
I am having troubles with even a single state-county combination at the block group level for ACS5 end years 2010-2014:
(using B01003 as an example)
````
> library(tidyverse)
> library(tidycensus)
> census_api_key("CENSUS KEY HERE", overwrite = TRUE)
>
> acs.2014.bg <- get_acs(geography = "block group",
+                        year = 2014,
+                        variables = B01003,
+                        geometry = FALSE,
+                        state = 42,
+                        county = 101,
+                        output = "wide")
Getting data from the 2010-2014 5-year ACS
Error: Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy.
````
This code works for ACS5 end years 2015-2017.

I tried the work around provided above: 
````
> get_state_demographic_data <- function(the_state,the_year) {
+   
+   options(tigris_use_cache = TRUE) #keep chached version of data
+   
+   # get all counties in given state
+   counties <- tidycensus::fips_codes %>%
+     dplyr::filter(state == the_state)
+   
+   # loop over counties and get tracts for each county
+   purrr::map(counties$county_code, 
+              ~ get_acs(
+                geography = 'block group',
+                table = c("B01003"),
+                state = the_state,
+                county = .x,
+                year = the_year,
+                survey = 'acs5',
+                geometry = TRUE,
+                cache_table = TRUE
+              )
+   ) %>% 
+     purrr::reduce(rbind)  # bind rows of all counties
+ }
> 
> test <- get_state_demographic_data('PA',2014)
Getting data from the 2010-2014 5-year ACS
Loading ACS5 variables for 2014 from table B01001 and caching the dataset for faster future access.
Using FIPS code '42' for state 'PA'
 Show Traceback
 
 Rerun with Debug
 Error: Your API call has errors.  The API message returned is error: unknown/unsupported geography heirarchy. 
````
I additionally tried calling the Census API directly:
https://api.census.gov/data/2014/acs5?get=B01003&for=state:42+county:101&key=CENSUS KEY HERE

But get a 404 error.

Is there another work around for using the Census API to call data across many tables/variables for 2010-2014 block groups?

**Comment by mfherman** [comment] 2019-02-13 15:35
@gpreston958 This is a known issue with Census API endpoints for years prior to 2015. Take a look here: https://github.com/walkerke/tidycensus/issues/136#issuecomment-445381782 for a little more discussion. My best advice at the moment would be to get block group data from [NHGIS](https://nhgis.org/) until the API issue is ironed out.

**Comment by walkerke** [comment] 2019-02-14 19:36
Thanks @gpreston958 @mfherman!  Yes the problem is that the new endpoints for 2010-2014 endyears require specifying a tract to perform block group queries.  I'm putting a request in with Census to allow for county wildcards as the old endpoints did, as making tract-by-tract API calls then stitching them together in tidycensus isn't a great solution performance-wise.  I'll post updates here.

**Comment by loganpowell** [comment] 2019-02-14 19:51
Calls to the ACS endpoints have changed and must now include a prequalifying `acs` before the product. E.g., https://api.census.gov/data/2014/acs/acs5?get=B01003_001E&for=county:101&in=state:42

As for the wildcard issue, the team is working on it atm. If your need is urgent, please don't hesitate to tell them so: cnmp.developers.list@census.gov

**Comment by walkerke** [comment] 2019-04-23 11:08
This issue is fixed in tidycensus master (0.9.2).

**Closed by walkerke** 2019-04-23 11:08 UTC

**Comment by gpresto** [comment] 2019-07-09 22:05
This may be related back to how the Census API handles the request, but I am again having issues with iterating across tracts/states for end-years prior to 2015.
```
library(tidyverse)
library(tidycensus)

# Sample states to iterate across
vars_states <- c(05,06,08)

# 2017 data works
dat_17 <- map_dfr(vars_states,
                  ~ get_acs(geography = "tract",
                            variables = "B01003_001",
                            year = 2017,
                            state = .x,
                            output = "wide"))
#> Getting data from the 2013-2017 5-year ACS
                     
# 2012 data fails
dat_12 <- map_dfr(vars_states,
                  ~ get_acs(geography = "tract",
                            variables = "B01003_001",
                            year = 2012,
                            state = .x,
                            output = "wide"))
#> Error in get_acs(geography = "tract", variables = "B01003_001", year = 2012, : object '.x' not found


# Workaround
dat_12 <- data.frame()
for(i in vars_states){
  acs <- get_acs(geography = "tract",
                 variables = "B01003_001",
                 year = 2012,
                 state = i,
                 output = "wide")
  df <- data.frame(acs)
  dat_12 <- rbind(dat_12, df)
}
```

While the workaround works, per se, it's indeed very slow. 

I tried tinkering around with the arguments and inputs and everything end-year 2015 onward seems to work fine while 2014 and prior the same error: "object .x not found"

**Comment by mfherman** [comment] 2019-07-10 00:05
Hey @gpresto, I just tested your code and it's working for me for both 2017 and 2012. I'm using the latest CRAN version of tidycensus, 0.9.2. Can you make sure you're running the most recent version of the package?

**Comment by gpresto** [comment] 2019-07-10 14:41
Without any package updating it seems to be working now, although quite slowly. Difficult to tell when the issue is an API bug or syntax error on my end. The error "object '.x' not found" had me worried it was my own error.
Slowness could be that I'm iterating over all tracts, all states, and 40 or so variables.
Thanks!
